-- AlterTable
ALTER TABLE `users` MODIFY `role` ENUM('ADMIN', 'MANAGER', 'SUPERVISOR', 'WORKER', 'HEAD', 'DEPUTY_HEAD', 'PROJECT_MANAGER', 'CHIEF_ENGINEER', 'ENGINEER', 'ASSISTANT_ENGINEER', 'TECHNICAL_OFFICER', 'SECRETARY', 'TRAINEE', 'OTHER') NOT NULL DEFAULT 'WORKER';
